#baseURL = "https://vijaypolsani.github.io/singlepane"
baseURL = "/"
themesDir = "themes"
theme = "hugo-serif-theme"
languageCode = "en-us"
title = "Single Pane"
subtitle = "Intelligent Signal Classification and Decison Management"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.88.0"

[params]
  # In most cases you will only want to set the google_analytics_id OR the google_tag_manager_id. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = false      # show / hide the contact box on the homepage
    show_services_button = false  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/singlepane-mobile.jpg"
    mobile_height = "20px"
    desktop = "images/logo/singlepane.jpg"
    desktop_height = "40px"
    alt = "Single Pane of Glass - Intelligent signal classification and decison management software."

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#f24088"
    black = "#2f2f41"
    white = "#ffffff"
    white_offset = "#f6f7ff"
    grey = "#5C5A5A"

  [params.seo]
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"
    meta_og_image = "https://www.zerostatic.io/theme/hugo-serif/hugo-serif-screenshot.png"

  [params.services]
    summary_truncate = 120 # How many characters to include in the summary of the services before truncating

  [params.team]
    summary_large_truncate = 120 # How many characters to include in the summary of the team bios (large layout) before truncating

#  [params.footer]
#    # copyright_text = 'Kernel Domain Inc <a class="kerneldomain" href="https://www.kerneldomain.com">www.kerneldomain.com</a>'
#    copyright_text = 'Kernel Domain Inc'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2

  [[menu.main]]
    name = "Strategy"
    url = "/strategy/"
    weight = 3

  [[menu.main]]
    name = "Community"
    url = "/community/"
    weight = 4

  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 5

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 7

  # Footer Menu
  [[menu.footer]]
    name = "COPYRIGHT © 2023 Single Pane Inc. All Rights Reservred."
  #  url = "/"
    weight = 1
